options:
  dns_refreshSeconds:
    type: int
    default: 60
    description: "The frequency at which Mesos-DNS updates DNS records based on information retrieved from the Mesos master. The default value is 60 seconds."
  dns_ttl:
    type: int
    default: 60
    description: "The time to live value for DNS records served by Mesos-DNS, in seconds. It allows caching of the DNS record for a period of time in order to reduce DNS request rate. ttl should be equal or larger than refreshSeconds. The default value is 60 seconds."
  dns_domain:
    type: string
    default: "mesos"
    description: "The domain name for the Mesos cluster. The domain name can use characters [a-z, A-Z, 0-9], - if it is not the first or last character of a domain portion, and . as a separator of the textual portions of the domain name. We recommend you avoid valid top-level domain names. The default value is mesos."
  dns_port:
    type: int
    default: 53
    description: "The port number that Mesos-DNS monitors for incoming DNS requests. Requests can be sent over TCP or UDP. We recommend you use port 53 as several applications assume that the DNS server listens to this port. The default value is 53."
  dns_timeout:
    type: int
    default: 5
    description: "The timeout threshold, in seconds, for connections and requests to external DNS requests. The default value is 5 seconds."
  dns_httpon:
    type: boolean
    default: true
    description: "A boolean field that controls whether Mesos-DNS listens for HTTP requests or not. The default value is true."
  dns_dsnon:
    type: boolean
    default: true
    description: "A boolean field that controls whether Mesos-DNS listens for DNS requests or not. The default value is true."
  dns_httpport: 
    type: int
    default: 8123
    description: "The port number that Mesos-DNS monitors for incoming HTTP requests. The default value is 8123."
  dns_externalon:
    type: boolean
    default: true
    description: "A boolean field that controls whether Mesos-DNS serves requests outside of the Mesos domain. The default value is true."
  dns_listener:
    type: string
    default: "0.0.0.0"
    description: "The IP address of Mesos-DNS. In SOA replies, Mesos-DNS identifies hostname mesos-dns.domain as the primary nameserver for the domain. It uses this IP address in an A record for mesos-dns.domain. The default value is '0.0.0.0', which instructs Mesos-DNS to create an A record for every IP address associated with a network interface on the server that runs the Mesos-DNS process."
  dns_SOAMname:
    type: string
    default: "root.ns1.mesos"
    description: "The MNAME field in the SOA record for the Mesos domain. The format is mailbox.domain, using a . instead of @. For example, if the email address is root@ns1.mesos, the email field should be root.mesos-dns.mesos. For details, see the RFC-1035. The default value is root.ns1.mesos."
  dns_SOARname:
    type: string
    default: "ns1.mesos"
    description: "TODO"
  dns_SOARefresh:
    type: int
    default: 60
    description: "The REFRESH field in the SOA record for the Mesos domain. For details, see the RFC-1035. The default value is 60."
  dns_SOARetry:
    type: int
    default: 600
    description: "The RETRY field in the SOA record for the Mesos domain. For details, see the RFC-1035. The default value is 600."
  dns_SOAExpire:
    type: int
    default: 86400
    description: "The EXPIRE field in the SOA record for the Mesos domain. For details, see the RFC-1035. The default value is 86400."
  dns_SOAMinttl:
    type: int
    default: 60
    description: "The minimum TTL field in the SOA record for the Mesos domain. For details, see the RFC-2308. The default value is 60."