#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

juju-log "Installing marathon on $JUJU_UNIT_NAME"
status-set maintenance "Fetching and installing marathon"

status-set maintenance "Fetching and installing docker"
# Install docker
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu

status-set maintenance "Fetching and installing marathon"

mkdir -p /opt/marathon-vars/
echo -n "" > /opt/marathon-vars/ZOOKEEPERS

docker pull mesoscloud/marathon:0.11.0-ubuntu

cp /etc/resolvconf/resolv.conf.d/head /etc/resolvconf/resolv.conf.d/head.backup

UNIT_PRIVATE_ADDRESS=`unit-get private-address`
HOSTNAME=`hostname`
echo "$UNIT_PRIVATE_ADDRESS $HOSTNAME" >> /etc/hosts
