#!/bin/bash

set -x

sudo service mesos-dns stop

set -e 

ZOOKEEPERS=`cat /opt/mesos-dns-vars/ZOOKEEPERS`

if [[ -n "$ZOOKEEPERS" ]]; then
    sudo service mesos-dns restart

    status-set active
else
    status-set waiting "Zookeeper relation is requred"
fi
