#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

juju-log "Installing zookeeper on $JUJU_UNIT_NAME"
status-set maintenance "Fetching and installing zookeeper"

status-set maintenance "Fetching and installing docker"
# Install docker
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu

status-set maintenance "Fetching and installing zookeeper"

docker pull mesoscloud/zookeeper:3.4.6-ubuntu-14.04