#!/bin/bash

set -x

OVERRIDE_HOSTNAME=`config-get override_hostname`
if [ "${OVERRIDE_HOSTNAME^^}" = "TRUE" ]; then
    IP=`unit-get private-address`
    HOSTNAME=`hostname`
    echo "$IP $HOSTNAME" >> /etc/hosts
fi

./hooks/start
