
---
- name: create work dir
  file: path={{ WORK_DIR }} state=directory

- name: get hostname
  shell: hostname -I | cut -d ' ' -f1
  register: local_host

- name: init charm state
  set_fact:
    UNIT_NAME_VAR: "{{ local_unit }}"
    HOSTNAME_VAR: "{{ local_host.stdout }}"
    CLUSTER_SEGMENT_VAR: "tools"
  changed_when: true
  notify: 
    - dump config
