#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

juju-log "Installing mesos-master on $JUJU_UNIT_NAME"

status-set maintenance "Fetching and installing docker"
# Install docker
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu

status-set maintenance "Pull mesos-master image"

docker pull mesoscloud/mesos-master:0.24.1-ubuntu

mkdir -p /opt/mesos-master-vars/
echo -n "" > /opt/mesos-master-vars/ZOOKEEPERS
